import { BaseLayout } from "@/components/wraps/BaseLayout";
import { LoadingProvider } from "@/hooks/useLoading";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LoadingProvider>
          <BaseLayout>{children}</BaseLayout>
        </LoadingProvider>
      </body>
    </html>
  );
}
